### PR TITLE
Issue 230/vm does not get cleaned up

### PR DESCRIPTION
**Pull request by kazaamjt**
# Description

Changes vm name to "{resource_name_prefix}".

# Merge procedure

Special merge procedure not required as this fixed tests and not module internals.

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [ ] ~Changelog entry~
- [ ] ~Version number is bumped to dev version~
- [ ] ~Code is clear and sufficiently documented~
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

### CODE REVIEW

**Comment by bartv** [comment]
If I read the fixtures correct the cleanup for virtual machines is done based on tags and not the name:

https://github.com/inmanta/aws/blob/master/tests/conftest.py#L110

You should also assign a reviewer or mark it as draft if it is in progress

**Comment by bartv** [comment]
> If I read the fixtures correct the cleanup for virtual machines is done based on tags and not the name:
> 
> https://github.com/inmanta/aws/blob/master/tests/conftest.py#L110
> 
> You should also assign a reviewer or mark it as draft if it is in progress

Name is a tag, so just a reviewer who is more awake then me!

**Comment by kazaamjt** [comment]
> 
> 
> If I read the fixtures correct the cleanup for virtual machines is done based on tags and not the name:
> 
> https://github.com/inmanta/aws/blob/master/tests/conftest.py#L110
> 
> You should also assign a reviewer or mark it as draft if it is in progress

I am so confused. I had tagged Arnaud and Sander as reviewers.

**Comment by arnaudsjs** [comment]
When a VM is created, the name of the VM is set as a tag (https://github.com/inmanta/aws/blob/b8fa63de4442eee31a02d111bbff161edac96b68/plugins/__init__.py#L755).

**Review by arnaudsjs — APPROVED** [review]
Looks good to me. However, the CI pipeline runs on releases so we have to release this. Or we can wait until the other aws ticket is merged as well. @sanderr What do you think?

**Review by sanderr — APPROVED** [review]

**Comment by sanderr** [comment]
@arnaudsjs do I understand correctly the fix you did yesterday will be sufficient until then, or do you expect we will encounter this issue again? In any case, I don't see any harm in a patch release.

**Comment by arnaudsjs** [comment]
> @arnaudsjs do I understand correctly the fix you did yesterday will be sufficient until then, or do you expect we will encounter this issue again? In any case, I don't see any harm in a patch release.

I am pretty confident this issue will happen again. But I am not sure how soon. I also don't see any harm in doing a release.

**Comment by kazaamjt** [comment]
> 
> 
> > @arnaudsjs do I understand correctly the fix you did yesterday will be sufficient until then, or do you expect we will encounter this issue again? In any case, I don't see any harm in a patch release.
> 
> I am pretty confident this issue will happen again. But I am not sure how soon. I also don't see any harm in doing a release.

I released v3.0.8

**Comment by kazaamjt** [comment]
Closed by commits cac8c59e76d79f4e6e62da2d759e56bb059976a9 and 2c335aa91408c172abc6a0eda951cae5aa30cef1

**Pull request closed without merging**
